### ISSUE TITLE
can not backup groups

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [mahdi-malv/getgitlab#1]
when I try to backup my repo in a group, I get error:
```
Traceback (most recent call last):
  File "getgitlab.py", line 112, in <module>
    for i in repos:
  File "getgitlab.py", line 14, in to_http_url
    return item['http_url_to_repo']
TypeError: string indices must be integers
```

**Comment by mahdi-malv** [comment]
Thanks for the report.

I've added `group` support to it.

```
python getgitlab.py --group group_name --token TOKEN
```
Feel free to test

Though, your user must be a member of the group (Your `token` needs to have access to groups as well)

[ChangeLog](https://github.com/mahdi-malv/getgitlab/blob/master/CHANGELOG.md#101)
